version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Docker/Dockerfile.api
    expose:
      - 5000
    labels:
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
  client:
    build:
      context: .
      dockerfile: Docker/Dockerfile.client
    labels:
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"
  proxy:
    image: traefik:latest
    command: "--api.insecure=true --providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
